# Generated by Django 6.0 on 2025-12-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='amenity_images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
