# Generated by Django 6.0 on 2025-12-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0003_coupon_villapricing_remove_amenity_amenity_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='amenity_image',
            field=models.ImageField(blank=True, null=True, upload_to='amenities/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(default=10),
        ),
    ]
