# Generated by Django 6.0 on 2025-12-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0004_amenity_amenity_image_alter_booking_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villapricing',
            name='weekday_price',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='villapricing',
            name='weekend_price',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=10),
        ),
    ]
