# Generated by Django 6.0 on 2025-12-18 07:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0005_alter_villapricing_weekday_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
