# Generated by Django 6.0 on 2025-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0006_alter_roomcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_guest_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='villapricing',
            name='extra_guest_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(default=15),
        ),
    ]
