# Generated by Django 6.0 on 2025-12-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0009_booking_payment_id_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tax_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
