# Generated by Django 6.0 on 2025-12-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0010_booking_tax_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='coupon_applied',
        ),
    ]
