# Generated by Django 6.0 on 2025-12-19 11:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0011_remove_booking_coupon_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='disc_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
