# Generated by Django 6.0 on 2025-12-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0012_booking_disc_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='slot_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
