# Generated by Django 6.0 on 2025-12-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0013_mainbanner_active_mainbanner_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'partial'), ('paid', 'Paid'), ('failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
