# Generated by Django 6.0 on 2025-12-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0014_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='slot_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slot_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='slot_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
