# Generated by Django 6.0 on 2025-12-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0016_blockeddate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('guest_email', 'check_in', 'check_out', 'payment_method'), name='unique_booking_guest_dates'),
        ),
    ]
