# Generated by Django 6.0 on 2025-12-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0017_booking_unique_booking_guest_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
