# Generated by Django 6.0 on 2026-01-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0019_alter_booking_payment_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_guest_dates',
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
