# Generated by Django 6.0 on 2026-03-25 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0020_remove_booking_unique_booking_guest_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resort.roomcategory'),
        ),
    ]
