# Generated by Django 6.0 on 2026-04-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0022_alter_offer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='terms',
        ),
    ]
