# Generated by Django 6.0 on 2026-04-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort', '0023_remove_offer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
