# Generated by Django 6.0 on 2026-01-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
